### ISSUE TITLE
Updating Shopping List / Pantry error

### ISSUE THREAD

**Issue by dandrewgarvin** [theRealFoodFinder/food-finder#66]
(node:44676) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'items' of undefined

I received this error when I created a new user, and tried to add items to my shopping cart. It may have something to do with the fact that it is a new user account, so default values are NULL?

**Comment by dandrewgarvin** [comment]
We may need to create a new row in the DB on pantries when a user is first created. That may help with this issue.

**Comment by FreeFlight-Code** [comment]
is this completed?
